services:
  - type: web
    name: my-map-backend2 # Замените на имя вашего сервиса, если оно отличается
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "22.16.0"
    # Команды, которые нужно выполнить перед сборкой
    preInstallCommands:
      - apt-get update && apt-get install -y wget gnupg
      - wget -qO - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      - sh -c 'echo "deb [arch=amd64,arm64,ppc64el] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      - apt-get update && apt-get install -y google-chrome-stable
