services:
  - type: web
    name: my-map-backend2 # Замените на имя вашего сервиса, если оно отличается
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "22.16.0"
    # Команды, которые нужно выполнить перед сборкой
    # Используем альтернативный способ установки Chrome, как рекомендовано Render
    preInstallCommands:
      # 1. Установка wget и gnupg для добавления ключа
      - apt-get update && apt-get install -y wget gnupg
      # 2. Добавление ключа Google
      - wget -qO - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      # 3. Добавление репозитория Google Chrome
      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      # 4. Обновление списка пакетов и установка Chrome
      - apt-get update && apt-get install -y google-chrome-stable
